# List

* https://docs.python.org/3/tutorial/datastructures.html
* https://www.programiz.com/python-programming/list
* https://developers.google.com/edu/python/lists

In [57]:
fruits = ['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']
print(fruits)

['orange', 'apple', 'pear', 'banana', 'kiwi', 'apple', 'banana']


In [58]:
print(fruits[2])

pear


In [59]:
print(fruits[-1])

banana


In [60]:
print(fruits[::2])

['orange', 'pear', 'kiwi', 'banana']


In [61]:
fruits.count('apple')

2

In [62]:
fruits.count('xyz')

0

In [63]:
fruits.index('banana')

3

In [64]:
fruits.index('banana',4)

6

In [65]:
if 'xyz' in fruits:
  fruits.index('xyz')

In [66]:
fruits.reverse()
fruits

['banana', 'apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [67]:
fruits.remove('banana')
fruits

['apple', 'kiwi', 'banana', 'pear', 'apple', 'orange']

In [68]:
fruits.append('grape')
fruits

['apple', 'kiwi', 'banana', 'pear', 'apple', 'orange', 'grape']

In [69]:
fruits.sort()
fruits

['apple', 'apple', 'banana', 'grape', 'kiwi', 'orange', 'pear']

## List as Stack

In [70]:
stack = [3,4,5]
stack

[3, 4, 5]

In [71]:
stack.append(6)
stack.append(7)
stack

[3, 4, 5, 6, 7]

In [72]:
stack.pop()

7

In [73]:
stack

[3, 4, 5, 6]

In [74]:
for x in stack:
  print(x)

3
4
5
6


## Matrix

In [75]:
matrix = [
          [1,2,3,4],
          [5,6,7,8],
          [9,10,11,12] ]
print(matrix)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [76]:
len(matrix[0])

4

In [77]:
n = []
for i in range(len(matrix)):
  for j in range(len(matrix[i])):
    n.append(matrix[i][j])
print(n)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [78]:
n = []
for sublist in matrix:
  for val in sublist:
    n.append(val)
print(n)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]


In [79]:
[ matrix[i][j] for i in range(len(matrix)) for j in range(len(matrix[i])) ]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

In [80]:
[ val for sublist in matrix for val in sublist ]

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]

# Dictionary

* https://realpython.com/python-dicts/
* https://www.programiz.com/python-programming/dictionary

In [81]:
MLB_team = {
    'Colorado' : 'Rockies',
    'Boston'   : 'Red Sox',
    'Minnesota': 'Twins',
    'Milwaukee': 'Brewers',
    'Seattle'  : 'Mariners'
    }
MLB_team

{'Boston': 'Red Sox',
 'Colorado': 'Rockies',
 'Milwaukee': 'Brewers',
 'Minnesota': 'Twins',
 'Seattle': 'Mariners'}

In [82]:
MLB_team['Boston']

'Red Sox'

In [83]:
MLB_team['Texas']

KeyError: ignored

In [84]:
print(MLB_team.get('Texas'))

None


In [85]:
MLB_team['Texas'] = 'Rangers'
MLB_team

{'Boston': 'Red Sox',
 'Colorado': 'Rockies',
 'Milwaukee': 'Brewers',
 'Minnesota': 'Twins',
 'Seattle': 'Mariners',
 'Texas': 'Rangers'}

In [90]:
MLB_team['Seattle'] = 'Seahawks'
MLB_team

{'Boston': 'Red Sox',
 'Colorado': 'Rockies',
 'Milwaukee': 'Brewers',
 'Minnesota': 'Twins',
 'Seattle': 'Seahawks',
 'Texas': 'Rangers'}

In [89]:
MLB_team.pop('Seattle')
# print(MLB_team)

'Seahawks'

In [91]:
del MLB_team['Seattle']
MLB_team

{'Boston': 'Red Sox',
 'Colorado': 'Rockies',
 'Milwaukee': 'Brewers',
 'Minnesota': 'Twins',
 'Texas': 'Rangers'}

In [93]:
list(MLB_team.keys())

['Colorado', 'Boston', 'Minnesota', 'Milwaukee', 'Texas']

In [94]:
list(MLB_team.values())

['Rockies', 'Red Sox', 'Twins', 'Brewers', 'Rangers']

# Numpy array / matrix

* https://numpy.org/doc/stable/user/quickstart.html
* https://www.programiz.com/python-programming/matrix

In [96]:
import numpy as np

In [100]:
print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [101]:
print(np.zeros((3,4)))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [102]:
print(np.ones((3,4), dtype=np.int16))

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [103]:
print(np.array([20,30,40,50]))

[20 30 40 50]


In [104]:
print(np.arange(4))

[0 1 2 3]


In [105]:
print(np.arange(0,2,0.3))

[0.  0.3 0.6 0.9 1.2 1.5 1.8]


In [111]:
print(np.arange(12).reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [113]:
a = np.array([20, 30, 40, 50])
print(a)

[20 30 40 50]


In [114]:
b = np.arange(4)
print(b)

[0 1 2 3]


In [116]:
a-b

array([20, 29, 38, 47])

In [117]:
a+b

array([20, 31, 42, 53])

In [118]:
b**2

array([0, 1, 4, 9])

In [119]:
a.dot(b)

260

In [120]:
A = np.array([[1, 1],
              [0, 1]])
print(A)

[[1 1]
 [0 1]]


In [121]:
B = np.array([[2, 0],
              [3, 4]])
print(B)

[[2 0]
 [3 4]]


In [122]:
A*B

array([[2, 0],
       [0, 4]])

In [123]:
A@B

array([[5, 4],
       [3, 4]])

In [124]:
A.dot(B)

array([[5, 4],
       [3, 4]])

In [125]:
a = np.arange(10)**3
print(a)

[  0   1   8  27  64 125 216 343 512 729]


In [126]:
a[2:5]

array([ 8, 27, 64])

In [127]:
a[:8:2]

array([  0,   8,  64, 216])

In [128]:
a[-1]

729

In [129]:
a[::-1]

array([729, 512, 343, 216, 125,  64,  27,   8,   1,   0])

In [130]:
C = np.array([[[  0,  1,  2],
               [ 10, 12, 13]],
              [[100, 101, 102],
               [110, 112, 113]]])
print(C)

[[[  0   1   2]
  [ 10  12  13]]

 [[100 101 102]
  [110 112 113]]]


In [131]:
print(C.shape)

(2, 2, 3)


In [132]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [133]:
b = a
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [137]:
b[1,:2] = 0
print(b)

[[ 0  1  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]]


In [138]:
a+b

array([[ 0,  2,  4,  6],
       [ 0,  0, 12, 14],
       [16, 18, 20, 22]])

In [139]:
a = np.array([[ 0,  1,  2,  3],
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [140]:
c = a.copy()
print(c)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [141]:
c[1,:2] = 0
print(c)

[[ 0  1  2  3]
 [ 0  0  6  7]
 [ 8  9 10 11]]


In [142]:
a+c

array([[ 0,  2,  4,  6],
       [ 4,  5, 12, 14],
       [16, 18, 20, 22]])

# Pandas dataframe

* https://pandas.pydata.org/docs/user_guide/10min.html
* https://pandas.pydata.org/pandas-docs/dev/getting_started/tutorials.html
* https://www.learndatasci.com/tutorials/python-pandas-tutorial-complete-introduction-for-beginners/

In [97]:
import pandas as pd

In [143]:
a = [1083, 1714, 2124, 3424, 3343, 3793]
print(a)

[1083, 1714, 2124, 3424, 3343, 3793]


In [144]:
s = pd.Series(a)
print(s)

0    1083
1    1714
2    2124
3    3424
4    3343
5    3793
dtype: int64


In [158]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/Artificial Intelligence/Data/courselist-spring22.csv')
print(df)

     Status Subject  Course Section    CRN                           Title  \
0      OPEN      CS    1063       1  20464     Intro to Comp Programming I   
1      OPEN      CS    1083       1  31537  Prog I for Computer Scientists   
2      OPEN      CS    1083       2  31538  Prog I for Computer Scientists   
3    CLOSED      CS    1083       3  31810  Prog I for Computer Scientists   
4      OPEN      CS    1083       4  35683  Prog I for Computer Scientists   
..      ...     ...     ...     ...    ...                             ...   
349    OPEN      CS    7316      22  37320           Doctoral Dissertation   
350    OPEN      CS    7316      23  37321           Doctoral Dissertation   
351    OPEN      CS    7316      24  37322           Doctoral Dissertation   
352    OPEN      CS    7316      25  37323           Doctoral Dissertation   
353    OPEN      CS    7316      26  37324           Doctoral Dissertation   

    Cred Meeting Days          Times              Meeting Type 

In [159]:
print(df.head())

   Status Subject  Course Section    CRN                           Title Cred  \
0    OPEN      CS    1063       1  20464     Intro to Comp Programming I    3   
1    OPEN      CS    1083       1  31537  Prog I for Computer Scientists    3   
2    OPEN      CS    1083       2  31538  Prog I for Computer Scientists    3   
3  CLOSED      CS    1083       3  31810  Prog I for Computer Scientists    3   
4    OPEN      CS    1083       4  35683  Prog I for Computer Scientists    3   

  Meeting Days          Times              Meeting Type  ...   Location  \
0           MW    4:00-5:15pm  Online only, at set time  ...              
1           TR    4:00-5:15pm     Traditional in-person  ...  NPB 1.202   
2           TR  10:00-11:15am     Traditional in-person  ...  NPB 1.202   
3          MWF  10:00-10:50am  Online only, at set time  ...              
4           TR    1:00-2:15pm     Traditional in-person  ...  NPB 1.238   

                          Instructor         Date Weeks  Seats

In [160]:
print(df.columns)

Index(['Status', 'Subject', 'Course', 'Section', 'CRN', 'Title', 'Cred',
       'Meeting Days', 'Times', 'Meeting Type', 'Campus', 'Location',
       'Instructor', 'Date', 'Weeks', 'Seats', 'Enrolled', 'Available',
       'Wait List', 'Final Exam', 'Fees'],
      dtype='object')


In [161]:
cols_to_drop = ['Meeting Days', 'Times', 'Meeting Type', 'Campus', 'Location', 'Date', 'Weeks', 'Final Exam', 'Wait List']
df = df.drop([x for x in cols_to_drop if x in df.columns], axis=1)
print(df.columns)
print(df.head())

Index(['Status', 'Subject', 'Course', 'Section', 'CRN', 'Title', 'Cred',
       'Instructor', 'Seats', 'Enrolled', 'Available', 'Fees'],
      dtype='object')
   Status Subject  Course Section    CRN                           Title Cred  \
0    OPEN      CS    1063       1  20464     Intro to Comp Programming I    3   
1    OPEN      CS    1083       1  31537  Prog I for Computer Scientists    3   
2    OPEN      CS    1083       2  31538  Prog I for Computer Scientists    3   
3  CLOSED      CS    1083       3  31810  Prog I for Computer Scientists    3   
4    OPEN      CS    1083       4  35683  Prog I for Computer Scientists    3   

                          Instructor  Seats  Enrolled  Available   Fees  
0               Rutherford, Linda B.     75        70          5  $111   
1  Gomez Morales, Mauricio Alejandro     60        32         28  $111   
2  Gomez Morales, Mauricio Alejandro     60        53          7  $111   
3                     Rathore, Heena     65        65     

In [162]:
print(df.dtypes)

Status        object
Subject       object
Course         int64
Section       object
CRN            int64
Title         object
Cred          object
Instructor    object
Seats          int64
Enrolled       int64
Available      int64
Fees          object
dtype: object


In [163]:
df = df.astype({'CRN':str})
print(df.dtypes)

Status        object
Subject       object
Course         int64
Section       object
CRN           object
Title         object
Cred          object
Instructor    object
Seats          int64
Enrolled       int64
Available      int64
Fees          object
dtype: object


In [164]:
df['Cred'] = pd.to_numeric(df['Cred'], errors='coerce')
print(df.dtypes)

Status         object
Subject        object
Course          int64
Section        object
CRN            object
Title          object
Cred          float64
Instructor     object
Seats           int64
Enrolled        int64
Available       int64
Fees           object
dtype: object


In [165]:
df['Fees'] = df['Fees'].str.replace('$','')
print(df[df['Course']==1714])

    Status Subject  Course Section    CRN                    Title  Cred  \
13    OPEN      CS    1714     0A1  36483  Computer Programming II   4.0   
14    OPEN      CS    1714     0AA  36484  Computer Programming II   NaN   
15    OPEN      CS    1714     0AB  36485  Computer Programming II   NaN   
16    OPEN      CS    1714     0B2  36622  Computer Programming II   4.0   
17    OPEN      CS    1714     0BA  36623  Computer Programming II   NaN   
18    OPEN      CS    1714     0BB  36626  Computer Programming II   NaN   
19    OPEN      CS    1714     0C3  36634  Computer Programming II   4.0   
20    OPEN      CS    1714     0CA  36635  Computer Programming II   NaN   
21  CLOSED      CS    1714     0CB  36638  Computer Programming II   NaN   
22    OPEN      CS    1714     0D4  36643  Computer Programming II   4.0   
23    OPEN      CS    1714     0DA  36646  Computer Programming II   NaN   
24    OPEN      CS    1714     0DB  36650  Computer Programming II   NaN   

          I

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  """Entry point for launching an IPython kernel.


In [166]:
df['Course'] == 1714

0      False
1      False
2      False
3      False
4      False
       ...  
349    False
350    False
351    False
352    False
353    False
Name: Course, Length: 354, dtype: bool

In [167]:
print(df[df['Course']==1714])

    Status Subject  Course Section    CRN                    Title  Cred  \
13    OPEN      CS    1714     0A1  36483  Computer Programming II   4.0   
14    OPEN      CS    1714     0AA  36484  Computer Programming II   NaN   
15    OPEN      CS    1714     0AB  36485  Computer Programming II   NaN   
16    OPEN      CS    1714     0B2  36622  Computer Programming II   4.0   
17    OPEN      CS    1714     0BA  36623  Computer Programming II   NaN   
18    OPEN      CS    1714     0BB  36626  Computer Programming II   NaN   
19    OPEN      CS    1714     0C3  36634  Computer Programming II   4.0   
20    OPEN      CS    1714     0CA  36635  Computer Programming II   NaN   
21  CLOSED      CS    1714     0CB  36638  Computer Programming II   NaN   
22    OPEN      CS    1714     0D4  36643  Computer Programming II   4.0   
23    OPEN      CS    1714     0DA  36646  Computer Programming II   NaN   
24    OPEN      CS    1714     0DB  36650  Computer Programming II   NaN   

          I

In [168]:
df = df.fillna(0)
print(df[df['Course']==1714])

    Status Subject  Course Section    CRN                    Title  Cred  \
13    OPEN      CS    1714     0A1  36483  Computer Programming II   4.0   
14    OPEN      CS    1714     0AA  36484  Computer Programming II   0.0   
15    OPEN      CS    1714     0AB  36485  Computer Programming II   0.0   
16    OPEN      CS    1714     0B2  36622  Computer Programming II   4.0   
17    OPEN      CS    1714     0BA  36623  Computer Programming II   0.0   
18    OPEN      CS    1714     0BB  36626  Computer Programming II   0.0   
19    OPEN      CS    1714     0C3  36634  Computer Programming II   4.0   
20    OPEN      CS    1714     0CA  36635  Computer Programming II   0.0   
21  CLOSED      CS    1714     0CB  36638  Computer Programming II   0.0   
22    OPEN      CS    1714     0D4  36643  Computer Programming II   4.0   
23    OPEN      CS    1714     0DA  36646  Computer Programming II   0.0   
24    OPEN      CS    1714     0DB  36650  Computer Programming II   0.0   

          I

In [169]:
print(df['Instructor'].unique())

['Rutherford, Linda B.' 'Gomez Morales, Mauricio Alejandro'
 'Rathore, Heena' 'Long, Byron L.' 'Roberson, Dawnlee J.' 'Staff'
 'Jointer, Stanley' 'Desai, Kevin' 'Banerjee, Jishnu'
 'Sherette, Jonathan L.' 'Heaps, John S.' 'Pritom, Mir Mehedi A.'
 'Yang, Zhongxiu' 'Arafat, Imtiaz Muhammad' 'Anderson, Benjamin R.'
 'Lu, Qi' 'Dutta, Anandi K.' 'Gibson, Matthew R.' 'Silvestro, Sam A.'
 "O'Hara, Steven A." 'Korkmaz, Turgay  .' 'Ruan, Jianhua'
 'Valadez, Juan M.' 'Wang, Wei' 'Ortiz, John A.' 'Murphy, Richard L.'
 'Arora, Ritu' 'Fernandez, Amanda S.' 'Harrison, Keith B.' 'Sandhu, Ravi'
 'Quarles, John P.' 'Zhu, Dakai' 'Ku, Bernard S.' 'Rutherford, James R.'
 'Slavin, Rocky L.' 'Najafirad, Peyman' 'Wang, Xiaoyin'
 'White, Gregory B.' 'Xie, Mimi' 'Lama, Palden' 'Jha, Sumit K.'
 'Boppana, Rajendra V.' 'Niu, Jianwei' 'Jadliwala, Murtuza'
 'Prasad, Sushil']


# Matplotlib

* https://matplotlib.org/stable/tutorials/index.html
* https://www.datacamp.com/tutorial/matplotlib-tutorial-python
* https://realpython.com/python-matplotlib-guide/
* https://www.geeksforgeeks.org/matplotlib-tutorial/

In [98]:
import matplotlib.pyplot as plt